const CountryCode = {
  AD: "AD",
  AE: "AE",
  AF: "AF",
  AG: "AG",
  AI: "AI",
  AL: "AL",
  AM: "AM",
  AO: "AO",
  AQ: "AQ",
  AR: "AR",
  AS: "AS",
  AT: "AT",
  AU: "AU",
  AW: "AW",
  AX: "AX",
  AZ: "AZ",
  BA: "BA",
  BB: "BB",
  BD: "BD",
  BE: "BE",
  BF: "BF",
  BG: "BG",
  BH: "BH",
  BI: "BI",
  BJ: "BJ",
  BL: "BL",
  BM: "BM",
  BN: "BN",
  BO: "BO",
  BQ: "BQ",
  BR: "BR",
  BS: "BS",
  BT: "BT",
  BV: "BV",
  BW: "BW",
  BY: "BY",
  BZ: "BZ",
  CA: "CA",
  CC: "CC",
  CD: "CD",
  CF: "CF",
  CG: "CG",
  CH: "CH",
  CI: "CI",
  CK: "CK",
  CL: "CL",
  CM: "CM",
  CN: "CN",
  CO: "CO",
  CR: "CR",
  CU: "CU",
  CV: "CV",
  CW: "CW",
  CX: "CX",
  CY: "CY",
  CZ: "CZ",
  DE: "DE",
  DJ: "DJ",
  DK: "DK",
  DM: "DM",
  DO: "DO",
  DZ: "DZ",
  EC: "EC",
  EE: "EE",
  EG: "EG",
  EH: "EH",
  ER: "ER",
  ES: "ES",
  ET: "ET",
  FI: "FI",
  FJ: "FJ",
  FK: "FK",
  FM: "FM",
  FO: "FO",
  FR: "FR",
  GA: "GA",
  GB: "GB",
  GD: "GD",
  GE: "GE",
  GF: "GF",
  GG: "GG",
  GH: "GH",
  GI: "GI",
  GL: "GL",
  GM: "GM",
  GN: "GN",
  GP: "GP",
  GQ: "GQ",
  GR: "GR",
  GS: "GS",
  GT: "GT",
  GU: "GU",
  GW: "GW",
  GY: "GY",
  HK: "HK",
  HM: "HM",
  HN: "HN",
  HR: "HR",
  HT: "HT",
  HU: "HU",
  ID: "ID",
  IE: "IE",
  IL: "IL",
  IM: "IM",
  IN: "IN",
  IO: "IO",
  IQ: "IQ",
  IR: "IR",
  IS: "IS",
  IT: "IT",
  JE: "JE",
  JM: "JM",
  JO: "JO",
  JP: "JP",
  KE: "KE",
  KG: "KG",
  KH: "KH",
  KI: "KI",
  KM: "KM",
  KN: "KN",
  KP: "KP",
  KR: "KR",
  KW: "KW",
  KY: "KY",
  KZ: "KZ",
  LA: "LA",
  LB: "LB",
  LC: "LC",
  LI: "LI",
  LK: "LK",
  LR: "LR",
  LS: "LS",
  LT: "LT",
  LU: "LU",
  LV: "LV",
  LY: "LY",
  MA: "MA",
  MC: "MC",
  MD: "MD",
  ME: "ME",
  MF: "MF",
  MG: "MG",
  MH: "MH",
  MK: "MK",
  ML: "ML",
  MM: "MM",
  MN: "MN",
  MO: "MO",
  MP: "MP",
  MQ: "MQ",
  MR: "MR",
  MS: "MS",
  MT: "MT",
  MU: "MU",
  MV: "MV",
  MW: "MW",
  MX: "MX",
  MY: "MY",
  MZ: "MZ",
  NA: "NA",
  NC: "NC",
  NE: "NE",
  NF: "NF",
  NG: "NG",
  NI: "NI",
  NL: "NL",
  NO: "NO",
  NP: "NP",
  NR: "NR",
  NU: "NU",
  NZ: "NZ",
  OM: "OM",
  PA: "PA",
  PE: "PE",
  PF: "PF",
  PG: "PG",
  PH: "PH",
  PK: "PK",
  PL: "PL",
  PM: "PM",
  PN: "PN",
  PR: "PR",
  PS: "PS",
  PT: "PT",
  PW: "PW",
  PY: "PY",
  QA: "QA",
  RE: "RE",
  RO: "RO",
  RS: "RS",
  RU: "RU",
  RW: "RW",
  SA: "SA",
  SB: "SB",
  SC: "SC",
  SD: "SD",
  SE: "SE",
  SG: "SG",
  SH: "SH",
  SI: "SI",
  SJ: "SJ",
  SK: "SK",
  SL: "SL",
  SM: "SM",
  SN: "SN",
  SO: "SO",
  SR: "SR",
  SS: "SS",
  ST: "ST",
  SV: "SV",
  SX: "SX",
  SY: "SY",
  SZ: "SZ",
  TC: "TC",
  TD: "TD",
  TF: "TF",
  TG: "TG",
  TH: "TH",
  TJ: "TJ",
  TK: "TK",
  TL: "TL",
  TM: "TM",
  TN: "TN",
  TO: "TO",
  TR: "TR",
  TT: "TT",
  TV: "TV",
  TW: "TW",
  TZ: "TZ",
  UA: "UA",
  UG: "UG",
  UM: "UM",
  US: "US",
  UY: "UY",
  UZ: "UZ",
  VA: "VA",
  VC: "VC",
  VE: "VE",
  VG: "VG",
  VI: "VI",
  VN: "VN",
  VU: "VU",
  WF: "WF",
  WS: "WS",
  XK: "XK",
  YE: "YE",
  YT: "YT",
  ZA: "ZA",
  ZM: "ZM",
  ZW: "ZW",
} as const;

type CountryCode = (typeof CountryCode)[keyof typeof CountryCode];

const toInt = (countryCode: CountryCode): Number => {
  switch (countryCode) {
    case CountryCode.AD:
      return 0;
    case CountryCode.AE:
      return 1;
    case CountryCode.AF:
      return 2;
    case CountryCode.AG:
      return 3;
    case CountryCode.AI:
      return 4;
    case CountryCode.AL:
      return 5;
    case CountryCode.AM:
      return 6;
    case CountryCode.AO:
      return 7;
    case CountryCode.AQ:
      return 8;
    case CountryCode.AR:
      return 9;
    case CountryCode.AS:
      return 10;
    case CountryCode.AT:
      return 11;
    case CountryCode.AU:
      return 12;
    case CountryCode.AW:
      return 13;
    case CountryCode.AX:
      return 14;
    case CountryCode.AZ:
      return 15;
    case CountryCode.BA:
      return 16;
    case CountryCode.BB:
      return 17;
    case CountryCode.BD:
      return 18;
    case CountryCode.BE:
      return 19;
    case CountryCode.BF:
      return 20;
    case CountryCode.BG:
      return 21;
    case CountryCode.BH:
      return 22;
    case CountryCode.BI:
      return 23;
    case CountryCode.BJ:
      return 24;
    case CountryCode.BL:
      return 25;
    case CountryCode.BM:
      return 26;
    case CountryCode.BN:
      return 27;
    case CountryCode.BO:
      return 28;
    case CountryCode.BQ:
      return 29;
    case CountryCode.BR:
      return 30;
    case CountryCode.BS:
      return 31;
    case CountryCode.BT:
      return 32;
    case CountryCode.BV:
      return 33;
    case CountryCode.BW:
      return 34;
    case CountryCode.BY:
      return 35;
    case CountryCode.BZ:
      return 36;
    case CountryCode.CA:
      return 37;
    case CountryCode.CC:
      return 38;
    case CountryCode.CD:
      return 39;
    case CountryCode.CF:
      return 40;
    case CountryCode.CG:
      return 41;
    case CountryCode.CH:
      return 42;
    case CountryCode.CI:
      return 43;
    case CountryCode.CK:
      return 44;
    case CountryCode.CL:
      return 45;
    case CountryCode.CM:
      return 46;
    case CountryCode.CN:
      return 47;
    case CountryCode.CO:
      return 48;
    case CountryCode.CR:
      return 49;
    case CountryCode.CU:
      return 50;
    case CountryCode.CV:
      return 51;
    case CountryCode.CW:
      return 52;
    case CountryCode.CX:
      return 53;
    case CountryCode.CY:
      return 54;
    case CountryCode.CZ:
      return 55;
    case CountryCode.DE:
      return 56;
    case CountryCode.DJ:
      return 57;
    case CountryCode.DK:
      return 58;
    case CountryCode.DM:
      return 59;
    case CountryCode.DO:
      return 60;
    case CountryCode.DZ:
      return 61;
    case CountryCode.EC:
      return 62;
    case CountryCode.EE:
      return 63;
    case CountryCode.EG:
      return 64;
    case CountryCode.EH:
      return 65;
    case CountryCode.ER:
      return 66;
    case CountryCode.ES:
      return 67;
    case CountryCode.ET:
      return 68;
    case CountryCode.FI:
      return 69;
    case CountryCode.FJ:
      return 70;
    case CountryCode.FK:
      return 71;
    case CountryCode.FM:
      return 72;
    case CountryCode.FO:
      return 73;
    case CountryCode.FR:
      return 74;
    case CountryCode.GA:
      return 75;
    case CountryCode.GB:
      return 76;
    case CountryCode.GD:
      return 77;
    case CountryCode.GE:
      return 78;
    case CountryCode.GF:
      return 79;
    case CountryCode.GG:
      return 80;
    case CountryCode.GH:
      return 81;
    case CountryCode.GI:
      return 82;
    case CountryCode.GL:
      return 83;
    case CountryCode.GM:
      return 84;
    case CountryCode.GN:
      return 85;
    case CountryCode.GP:
      return 86;
    case CountryCode.GQ:
      return 87;
    case CountryCode.GR:
      return 88;
    case CountryCode.GS:
      return 89;
    case CountryCode.GT:
      return 90;
    case CountryCode.GU:
      return 91;
    case CountryCode.GW:
      return 92;
    case CountryCode.GY:
      return 93;
    case CountryCode.HK:
      return 94;
    case CountryCode.HM:
      return 95;
    case CountryCode.HN:
      return 96;
    case CountryCode.HR:
      return 97;
    case CountryCode.HT:
      return 98;
    case CountryCode.HU:
      return 99;
    case CountryCode.ID:
      return 100;
    case CountryCode.IE:
      return 101;
    case CountryCode.IL:
      return 102;
    case CountryCode.IM:
      return 103;
    case CountryCode.IN:
      return 104;
    case CountryCode.IO:
      return 105;
    case CountryCode.IQ:
      return 106;
    case CountryCode.IR:
      return 107;
    case CountryCode.IS:
      return 108;
    case CountryCode.IT:
      return 109;
    case CountryCode.JE:
      return 110;
    case CountryCode.JM:
      return 111;
    case CountryCode.JO:
      return 112;
    case CountryCode.JP:
      return 113;
    case CountryCode.KE:
      return 114;
    case CountryCode.KG:
      return 115;
    case CountryCode.KH:
      return 116;
    case CountryCode.KI:
      return 117;
    case CountryCode.KM:
      return 118;
    case CountryCode.KN:
      return 119;
    case CountryCode.KP:
      return 120;
    case CountryCode.KR:
      return 121;
    case CountryCode.KW:
      return 122;
    case CountryCode.KY:
      return 123;
    case CountryCode.KZ:
      return 124;
    case CountryCode.LA:
      return 125;
    case CountryCode.LB:
      return 126;
    case CountryCode.LC:
      return 127;
    case CountryCode.LI:
      return 128;
    case CountryCode.LK:
      return 129;
    case CountryCode.LR:
      return 130;
    case CountryCode.LS:
      return 131;
    case CountryCode.LT:
      return 132;
    case CountryCode.LU:
      return 133;
    case CountryCode.LV:
      return 134;
    case CountryCode.LY:
      return 135;
    case CountryCode.MA:
      return 136;
    case CountryCode.MC:
      return 137;
    case CountryCode.MD:
      return 138;
    case CountryCode.ME:
      return 139;
    case CountryCode.MF:
      return 140;
    case CountryCode.MG:
      return 141;
    case CountryCode.MH:
      return 142;
    case CountryCode.MK:
      return 143;
    case CountryCode.ML:
      return 144;
    case CountryCode.MM:
      return 145;
    case CountryCode.MN:
      return 146;
    case CountryCode.MO:
      return 147;
    case CountryCode.MP:
      return 148;
    case CountryCode.MQ:
      return 149;
    case CountryCode.MR:
      return 150;
    case CountryCode.MS:
      return 151;
    case CountryCode.MT:
      return 152;
    case CountryCode.MU:
      return 153;
    case CountryCode.MV:
      return 154;
    case CountryCode.MW:
      return 155;
    case CountryCode.MX:
      return 156;
    case CountryCode.MY:
      return 157;
    case CountryCode.MZ:
      return 158;
    case CountryCode.NA:
      return 159;
    case CountryCode.NC:
      return 160;
    case CountryCode.NE:
      return 161;
    case CountryCode.NF:
      return 162;
    case CountryCode.NG:
      return 163;
    case CountryCode.NI:
      return 164;
    case CountryCode.NL:
      return 165;
    case CountryCode.NO:
      return 166;
    case CountryCode.NP:
      return 167;
    case CountryCode.NR:
      return 168;
    case CountryCode.NU:
      return 169;
    case CountryCode.NZ:
      return 170;
    case CountryCode.OM:
      return 171;
    case CountryCode.PA:
      return 172;
    case CountryCode.PE:
      return 173;
    case CountryCode.PF:
      return 174;
    case CountryCode.PG:
      return 175;
    case CountryCode.PH:
      return 176;
    case CountryCode.PK:
      return 177;
    case CountryCode.PL:
      return 178;
    case CountryCode.PM:
      return 179;
    case CountryCode.PN:
      return 180;
    case CountryCode.PR:
      return 181;
    case CountryCode.PS:
      return 182;
    case CountryCode.PT:
      return 183;
    case CountryCode.PW:
      return 184;
    case CountryCode.PY:
      return 185;
    case CountryCode.QA:
      return 186;
    case CountryCode.RE:
      return 187;
    case CountryCode.RO:
      return 188;
    case CountryCode.RS:
      return 189;
    case CountryCode.RU:
      return 190;
    case CountryCode.RW:
      return 191;
    case CountryCode.SA:
      return 192;
    case CountryCode.SB:
      return 193;
    case CountryCode.SC:
      return 194;
    case CountryCode.SD:
      return 195;
    case CountryCode.SE:
      return 196;
    case CountryCode.SG:
      return 197;
    case CountryCode.SH:
      return 198;
    case CountryCode.SI:
      return 199;
    case CountryCode.SJ:
      return 200;
    case CountryCode.SK:
      return 201;
    case CountryCode.SL:
      return 202;
    case CountryCode.SM:
      return 203;
    case CountryCode.SN:
      return 204;
    case CountryCode.SO:
      return 205;
    case CountryCode.SR:
      return 206;
    case CountryCode.SS:
      return 207;
    case CountryCode.ST:
      return 208;
    case CountryCode.SV:
      return 209;
    case CountryCode.SX:
      return 210;
    case CountryCode.SY:
      return 211;
    case CountryCode.SZ:
      return 212;
    case CountryCode.TC:
      return 213;
    case CountryCode.TD:
      return 214;
    case CountryCode.TF:
      return 215;
    case CountryCode.TG:
      return 216;
    case CountryCode.TH:
      return 217;
    case CountryCode.TJ:
      return 218;
    case CountryCode.TK:
      return 219;
    case CountryCode.TL:
      return 220;
    case CountryCode.TM:
      return 221;
    case CountryCode.TN:
      return 222;
    case CountryCode.TO:
      return 223;
    case CountryCode.TR:
      return 224;
    case CountryCode.TT:
      return 225;
    case CountryCode.TV:
      return 226;
    case CountryCode.TW:
      return 227;
    case CountryCode.TZ:
      return 228;
    case CountryCode.UA:
      return 229;
    case CountryCode.UG:
      return 230;
    case CountryCode.UM:
      return 231;
    case CountryCode.US:
      return 232;
    case CountryCode.UY:
      return 233;
    case CountryCode.UZ:
      return 234;
    case CountryCode.VA:
      return 235;
    case CountryCode.VC:
      return 236;
    case CountryCode.VE:
      return 237;
    case CountryCode.VG:
      return 238;
    case CountryCode.VI:
      return 239;
    case CountryCode.VN:
      return 240;
    case CountryCode.VU:
      return 241;
    case CountryCode.WF:
      return 242;
    case CountryCode.WS:
      return 243;
    case CountryCode.XK:
      return 244;
    case CountryCode.YE:
      return 245;
    case CountryCode.YT:
      return 246;
    case CountryCode.ZA:
      return 247;
    case CountryCode.ZM:
      return 248;
    case CountryCode.ZW:
      return 249;
  }
};

export { CountryCode, toInt };
